apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  params:
    - name: IMAGE
      description: Docker image repository name
      default: joeshiett/nodejs-app
    - name: TAG
      description: Tag value
      default: latest
  workspaces:
    - name: linked-workspace
      optional: true
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: linked-workspace
      params:
        - name: url
          value: https://github.com/joeshiett/tekton-test
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build-push-image
      taskRef:
        name: buildah
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: linked-workspace
      params:
        - name: IMAGE
          value: $(params.IMAGE):$(params.TAG)
        - name: CONTEXT
          value: "tekton"
				- name: DOCKERFILE
          value: "src/Dockerfile"
        - name: FORMAT
          value: "docker"
    - name: create-deployment
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            kubectl apply --filename manifest/deploy.yml
      workspaces:
        - name: manifest-dir
          workspace: linked-workspace
	